### PR TITLE
Feature/add prices

### LINKED ISSUE #200: Allow input of multiple price-objects
Add functionality for adding multiple price objects fo event. Form should include Add new Price info -button, which adds a new 3-part set of fields identical to one shown by default.

As part of changes, move Free-checkbox to top of segment. Allow adding new Price info only when Free-ceckbox is unchecked.

API support for multiple price objects already exists.

multiple-price-info

### PR DESCRIPTION
**Pull request by jonraem**
Add the ability to add, edit and remove price (offer) information.

Fixes #200.

### CODE REVIEW

**Comment by jonraem** [comment]
May need API support for a separate `is_free` property for the whole event. Currently, offer-specific  `is_free` property causes some problems when submitting.

Alternatively first offer field can be made undeletable.

**Comment by jonraem** [comment]
How does this look now?

**Comment by Rikuoja** [comment]
Couldn't test due to merge conflicts, my rebase failed :/

**Comment by jonraem** [comment]
How's it now?

**Pull request merged**
