### PR TITLE
Feature/346 new event organization select

### PR DESCRIPTION
**Pull request by dotanthanh**
PR resolving issue #346:
- add a selection for publisher when creating a new event using user's admin organizations
- the publisher information is shown in editting form, though not editable

Signed-off-by: Thanh Do <thanh.do@digia.com>

### CODE REVIEW

**Comment by dotanthanh** [comment]
> Since often the publisher will often be determined automatically from the user default admin org (`organization` in the user json), I think it should be already selected in the list and marked as required. (The backend logic marks that as the publisher anyway if no publisher is selected.)
> 
> That way, the user will not be confused by the new field, and the right value is automatically shown when creating a new event.
> 
> Otherwise, looks very good!

updated

**Comment by aleksisalonen** [comment]
The user can now empty the publisher field and leave the field empty. 

We should just remove that posibility from the form.

**Comment by aleksisalonen** [comment]
Also, it would be better if the single possible publisher-type would be dispayed in the style of the Location ID.

**Comment by Rikuoja** [comment]
Okay, since this is already merged perhaps @dotanthanh can do these changes in a new PR?

**Comment by Rikuoja** [comment]
Also, I'm getting a new sentry error `TypeError: Cannot read property 'map' of null` from https://github.com/City-of-Helsinki/linkedevents-ui/blob/master/src/actions/organization.js#L24 .

Apparently the user object may have `adminOrganizations` `null` if the user is not logged in. This is not a problem in logged in use, but perhaps it's still better that the form doesn't crash for anonymous users.

**Pull request merged**
