### PR TITLE
fix datepicker not show value

### PR DESCRIPTION
**Pull request by dotanthanh**
When choose a date from the datepicker in SearchBar, the changed value is not shown. This is a fix for that.

Signed-off-by: Thanh Do <thanh.do@digia.com>

### CODE REVIEW

**Comment by aleksisalonen** [comment]
If this issue relates to the Search events -view, there is a another small *new* issue relating to it:

Using a wildcard (asterisk, "*") in the search seems to crash the search. Previously a wildcard could be used in conjunction with the datepickers to search for all events on a given date.

**Comment by Rikuoja** [comment]
Why would you use * instead of empty text field?

**Comment by Rikuoja** [comment]
Weird, I thought the search should work with an empty query string. Apparently it doesn't. Hm.

**Comment by Rikuoja** [comment]
Yeah. I'm flabbergasted, as I didn't even know the API search supported wildcards.

**Comment by aleksisalonen** [comment]
In any case the goal is for (Helsinki Marketing) to be able to searches based solely on dates. 

The *-error as such is trivial if this can be accomplished in some other way on the search-endpoint.

**Comment by Rikuoja** [comment]
Nope, it cannot be used without * , and I had no idea this functionality existed in the first place. I've always used the search endpoint with some text.

**Comment by Rikuoja** [comment]
However, the wildcard * works just fine for me on the test server :D How did you get a crash?

**Comment by aleksisalonen** [comment]
Yesterday a [date]–[date]+* resulted in an empty screen.

Today I can only reproduce it with using just the *. 

I guess the good news is it is now working for the intended purpose, althought that can't be said for sure for the live data, which is much more voluminous.

**Comment by Rikuoja** [comment]
Hm, so what in your opinion should we do if the user just enters * but no dates?

**Comment by Rikuoja** [comment]
The default in the search API, if dates are not given, is to return events in the near future with the given string. So * should result all events in the near future, but I can't guarantee their order will make any sense.

**Comment by Rikuoja** [comment]
It does look like, however, that it is returning events still going on today first, if you just search the API with * and no dates. So it could be usable, if anybody ever needs that.

**Comment by aleksisalonen** [comment]
The bare *-search as just is not really necessary. 

As I hinted at above, I think we should just make sure a large number of results – that could be achieved with the right date–date+*-combo – does not crash the search.

**Comment by Rikuoja** [comment]
I don't think it will ever crash. It just returns 100 top events, because that is the maximum page size in the API.

So if we need more than 100 events in the given range, we have to build pagination on the search page.

**Comment by Rikuoja** [comment]
I am actually getting a crash `Cannot read property 'fi' of null` in the search now.

So it has nothing to do with event numbers. The search crashes if we have an event that doesn't have a Finnish name :D

**Comment by Rikuoja** [comment]
Probably the same for other parts of the form, I've never tried what happens if the listing, or preview, or editor has an event with no Finnish name.

**Comment by Rikuoja** [comment]
Or, hm, that would indicate it might be an event with completely missing name, or some other property missing. Such things can lurk in the data, so the UI should survive that.

**Comment by aleksisalonen** [comment]
Ok, so not related to this PR, but good thing we caught it anyway. (It did have a certain affinity to volumes.)

**Comment by Rikuoja** [comment]
Oh yes, statistically there definitely is a significant correlation between the number of events displayed and the probability of one of them having missing data.

**Comment by Rikuoja** [comment]
Also, it is more likely for an event with no text to turn up in search if we are not searching for a specific text :D

**Comment by aleksisalonen** [comment]
Any random gargle noices would do :)

**Comment by aleksisalonen** [comment]
Or is nothing considered something as well? The French seem to think so...

**Comment by Rikuoja** [comment]
Luckily we use Unicode so we could use the International Phonetic Alphabet to encode any gargles in Linkedevents.

**Pull request merged**
