### PR TITLE
Raven reporter structural fixing

### PR DESCRIPTION
**Pull request by jussiarpalahti**
Get user and debug message separate from redux state for easier reporting.

### CODE REVIEW

**Comment by jussiarpalahti** [comment]
@Rikuoja For the next 5 years?

**Comment by jussiarpalahti** [comment]
Ugh. I just use Prettier, and that's not enough for the format check apparently.

**Comment by Rikuoja** [comment]
Ah ok so this just needs some minor linting @jussiarpalahti ?

**Comment by jussiarpalahti** [comment]
@Rikuoja Yeah. I went and done stupid by asking if we should start to use Prettier and not care about linters no more. Predictably that went nowhere. I'll fix those errors as linter would like.

**Comment by Rikuoja** [comment]
Ah well, I didn't realize you asked that! Your opinion here probably counts more than most, would you suggest that?

**Comment by jussiarpalahti** [comment]
For new projects using Prettier is a given.

Older projects are trickier since Git history will invariably get (more) messy. I'll do repo wide formatting test in my fork and we'll see how that looks.

**Comment by vikoivun** [comment]
KuVa folks (actually Panu), thought that the best way would be to format one file at a time, as they are changed.

**Comment by jussiarpalahti** [comment]
Well, it's not quite that simple. You'd have to remember to use format manually in a separate commit, which is hard to remember and takes discipline.. Or make a bot that goes through changed files afterwards to re-format them. Otherwise you risk missing actual modifications for format change noise in commits.

**Comment by jussiarpalahti** [comment]
@Rikuoja 3/4 checks pass now. Erroring build prints output from Sass install and stops... I'd wager that's not due to linting errors 🤷‍♂

**Comment by Rikuoja** [comment]
Nope, that's a node12 issue fixed in master.

**Pull request merged**
