### PR TITLE
basic smoke tests for ui

### PR DESCRIPTION
**Pull request by tkivela**
Jest smoke tests for 
Front page (event listing renders with mock data)
Event search page (event search renders with mock data)
Event create form (event form renders when empty)
Event create form (event form renders with mock data)

Still missing following:
Event add image form (add image form renders with mock data)
Create repeating event form (create repeating event form renders with existing mock data)

Tried to do tests for image add form but found it to be a little bit difficult to test with current image implementation and did not want to change implementation of functionalities because of the tests.

This PR also fixes Snackbar bug which caused the Snackbar to stay open and not close automatically. This bug had creeped in because Material-UI v1 API changes to Snackbar -component.

### CODE REVIEW

**Comment by tkivela** [comment]
Textfield validation has to be manually checked because of this PR changes line src/components/HelFormFields/HelTextField.js:135. This line used this.refs.text.getValue() to read input value which failed in jest tests and it has been changed to use value from components state. I tested it and noticed no difference in previous behaviours.

**Comment by tkivela** [comment]
Travis CI build seems to be using "npm install" to install node dependencies, shouldn't it use "yarn" to get the correct package versions? Now the travis build seems to be failing, and it might be due different package versions :(

**Comment by jussiarpalahti** [comment]
So it does. I put out a PR, let's see how that does.

**Comment by jussiarpalahti** [comment]
Ok, Node LTS meaning version 8.x seems to work. However, newest node doesn't because we have a limit on our package.json to 8 and node is already on 9.x.

@tkivela perhaps we could declare code works on 8.x and newer?

**Comment by jussiarpalahti** [comment]
Also, could you make the same change in your PR's travis.yml so we can check tests work with yarn?

Probably at some point need to add test matrix which installs on yarn and npm 5 or newer.

**Comment by Rikuoja** [comment]
@jussiarpalahti Is this close to working condition? Couldn't exactly make sense whether everything is working as planned.

**Comment by dotanthanh** [comment]
attempt to revive the PR:
- update with master
- further setup test environment (add enzyme, config jest)
- re-organize mocks data to separate place
- some changes to test suites (mostly shallow)
- some script for `.travis.yml`, hope it works

**Comment by dotanthanh** [comment]
It seems that Node is shipped with its own Intl with default to english only, which override `react-intl` and cause the snapshot mismatch. Reference to the issue [here](https://github.com/yahoo/react-intl/issues/1112) and [here](https://github.com/yahoo/react-intl/issues/1179)

**Pull request merged**
