### PR TITLE
258 webpack and react version upgrades

### LINKED ISSUE #258: Update webpack and react to latest versions, if possible

### PR DESCRIPTION
**Pull request by tkivela**
resolves #258 . Upgraded Webpack and React versions.

### CODE REVIEW

**Comment by tkivela** [comment]
Did this pull request a little bit too soon, there's still some versioning conflicts.

**Comment by Rikuoja** [comment]
Also, the title bar and button fonts seem to have changed for some reason, with horrendous consequences to user name vertical positioning: 
image

**Comment by Rikuoja** [comment]
And something else seems to be funny with the buttons too, because all of a sudden they have two different colors (purple and grey?), instead of the old blue in both buttons:

image

**Comment by Rikuoja** [comment]
Oh, and vertical positioning is off in the buttons too! So it's the same font problem as in the title bar.

**Comment by tkivela** [comment]
Fixed font sizes, button colors, icon vertical alignment. Also noticed that delete icon was missing from subevent delete button so I added that in the mix too.

**Pull request merged**
