### PR TITLE
Disallow empty strings (WIP)

### LINKED ISSUE #265: Disallow empty string in description and short description fields
Currently the form validation will allow for empty strings in the description (and presumably short description) field(s). 

This should be changed, so that user-added empty strings will trigger the empty field -warning.

### PR DESCRIPTION
**Pull request by niglu1**
This PR fixes #265  and #436

### CODE REVIEW

**Comment by Rikuoja** [comment]
Hm, is this meant to assess bug https://github.com/City-of-Helsinki/linkedevents-ui/issues/436 or bug https://github.com/City-of-Helsinki/linkedevents-ui/issues/265 , or both? Looking at the current code, is https://github.com/City-of-Helsinki/linkedevents-ui/issues/265 actually still an issue, since the length is checked already?

**Comment by niglu1** [comment]
Yes sorry, it fixes both. Shouldn't be an issue as the value length will be 0 after whitespace is trimmed.

**Comment by Rikuoja** [comment]
Okay, can @aleksisalonen verify that in master, #265 is already fixed?

**Comment by Rikuoja** [comment]
Also, could you refer to the fixed issue in the commit message, so the issue will be closed automatically when I merge this? 😄

**Comment by Rikuoja** [comment]
Okay, I added comments to issue https://github.com/City-of-Helsinki/linkedevents-ui/issues/265 , could be that this doesn't fix that issue yet =)

**Comment by Rikuoja** [comment]
I believe that we have to check *all* language fields present, so that none of them is empty. Currently, it is enough that one language passes the check.

**Comment by niglu1** [comment]
> I believe that we have to check _all_ language fields present, so that none of them is empty. Currently, it is enough that one language passes the check.

This is true. I'll fix that.

**Comment by aleksisalonen** [comment]
265 is already fixed, yes. 436 (spaces as only content) is still possible both in test and production.

**Comment by niglu1** [comment]
@Rikuoja, @aleksisalonen I changed the "required multi-language field" validation to check that _all_ values pass the empty string / whitespace validation.

**Comment by Rikuoja** [comment]
Merged, so @aleksisalonen can now try how it works on linkedevents.hel.ninja!

**Comment by aleksisalonen** [comment]
Yes, works as intended, thanks!

**Pull request merged**
