### PR TITLE
Added sorting labels to event listing

### LINKED ISSUE #191: Allow manual sorting in Tapahtumien hallinta
Allow user to sort events in Tapahtumien hallinta view according to event heading, start date, end date and last modified date.

Standard sorting functionality: clicking on any given sort condition sorts events accordingly and adds a ▼-symbol next to its name. A second click on the same condition will sort the events in reverse order and add a ▲-symbol. 

▼-symbol should be displayed by default next to the Modified last -column heading.

### PR DESCRIPTION
**Pull request by tkivela**
resolves #191.
The sorting by event name is already in place (it will pass "name" as sort parameter) event though the backend might not yet support it.

The sorting dispatches a new REQUEST_USER_EVENTS event which calls the API to get the new listing with defined sort parameter. The fetching of events causes the event listing table to disappear for a second (which is the same way it was before when navigating to the tapahtumat-tab). It might be a good idea to do a new Issue in which we would implement somekind of "loading" spinner in place of table during API fetch.

### CODE REVIEW

**Comment by tkivela** [comment]
I'll look first into adding a spinner to the control while loading, I think it should'nt be too big job. Material-UI guys have recommended to use https://github.com/DevExpress/devextreme-reactive/tree/master/packages/dx-react-grid-material-ui control for advanced scenarios (which has all the bells and whistles) but lets try with vanilla material-ui table first.

**Comment by Rikuoja** [comment]
Oh, and perhaps we want to change the pagination bar font color to white, so it is better discernible on the dark blue background?

**Comment by Rikuoja** [comment]
And one more thing :) Now the default sorting for sorting with name is descending, so the last events are shown first when the user first clicks the "Nimi" column. This is kinda counterintuitive so i'm afraid we'll have to have a special default for the name column where it will order them ascending, not descending, at first click :D

**Comment by tkivela** [comment]
Good points @Rikuoja ! I pushed a commit in which I changed pagination bar color to white, removed unused 'page' parameter from fetchUserEvents action and changed default sort order for "name" column to ascending.

Like you guessed the API's page parameter begins from 1 but TablePagination component we use uses 0 based counting. That's why we add to paginationPage variable when passing it to API. I commented that to the code so it's clearer.

**Pull request merged**
