### PR TITLE
Fix event title field text disappearing when editing the image caption field

### PR DESCRIPTION
**Pull request by jpaakko**
This pull request fixes issue https://github.com/City-of-Helsinki/linkedevents-ui/issues/537.

The event title disappeared because the image caption field's name attribute used the "name" value and was defined as a HelTextField element. The HelTextField element updates the store on the blur event and because the name of the caption field was "name", it collided with the event's title which is also stored in the store under the "name" key. Thus, the image caption field overrode the event title. Since the event title is an object and the image caption just a string, the event title appeared as an empty field in the UI.

The fix is to replace the HelTextField elements with ordinary TextField elements.

### CODE REVIEW

**Comment by Rikuoja** [comment]
Hm. Looks like the image name is initialized to the component state by the imageEdit prop, so actually I believe it should not be set back to the global store at all? Rather, it should be saved in the imageEdit component and in the image in the backend??

**Comment by jpaakko** [comment]
> 
> 
> Good catch, reproduced the bug myself!
> 
> The only caveat here is that removing the validations (and using regular TextField component) means the user can no longer see the character count under the alt text and caption fields:
> 
> image
> 
> I wonder if this could be done by retaining the HelTextField component, i.e. by changing the name of the `"name"` field in this dialog to something like `"imageName"` or `"caption"`? Then, of course, it would have to be changed in the store as well?

Good point! I didn't notice myself that the character count feature got removed. But that's obvious now since the feature is tied to the `HelTextField` component. This also explains why the `photographerName` field used a `TextField` component instead of a `HelTextField` component since the `photographerName` field doesn't have any validation rules.

> Hm. Looks like the image name is initialized to the component state by the imageEdit defaultName prop, so actually I believe any image name should not be set back to the global store at all? Rather, it should be saved in the imageEdit component and in the image in the backend??

Yes, I agree. Currently, I don't see any use of saving the `altText` or `name` fields to the global store by the `HelTextField` component. The `ImageEdit` component already calls the `postImage` action on submit and the `postImage` action saves the image metadata to the backend and calls the `setData` action which updates the global store with the image metadata.

I also got a feeling that storing the field values to the global store on the blur event in the `HelTextField` component might not be a good idea. This causes the `HelTextField` component to be tightly coupled with the global store. In other words, the component can't currently be used together with fields that don't need to be saved to the global store as might be the case with the image metadata fields.

Actually, currently the `HelTextField` component saves the values of the image metadata fields to the wrong location in the state tree. It doesn't save them in `editor.values.image` but rather in `editor.values` which causes also the conflict with the event title.

But now when I looked more carefully, I stumbled upon another bug. After uploading a new image, the `alt-text`, `caption`, and `photographer` fields appear empty for all images. Steps to reproduce:

1. Click the `Create a new event` button
1. Click the image upload area to add a new image
1. Click the `Upload image from your hard disk` button
1. Fill in the image metadata fields and click the `Save image` button
1. Select any image and click the `Edit the selected image` button
1. All the image metadata fields appear empty

Can you reproduce this bug?

Clearly, I need to take a closer look on this issue and improve on the fix 🙂

**Comment by jpaakko** [comment]
I happened to stumble upon some more bugs related to `ImagePicker`. All of the ones i stumbled upon should be fixed by the latest changes.

I also reverted the replacement of `HelTextField` components with `TextField` components and fixed the underlying issue in another way.

Hopefully, most of the bugs related to `ImagePicker` are now fixed.

**Comment by jpaakko** [comment]
> 
> 
> Looks excellent, should fix a few nagging issues!
> 
> Couldn't find the bug you reported from the issue list, but there is #523 which suspiciously looks like something that this PR might fix?

Nice, good that it fixed some other issues too!

**Pull request merged**
