### PR TITLE
433: Display event publisher in event preview

### PR DESCRIPTION
**Pull request by rBoost**
https://github.com/City-of-Helsinki/linkedevents-ui/issues/433

Add publisher information under event actions and under event location for event page.

Added also a rest API client for fetching the publisher's information. 
I also refactored and cleaned a bit the event page/event details code.

### CODE REVIEW

**Comment by rBoost** [comment]
> Okay, so apparently a new HTTP API client (axios) was added here. What is the use case, i.e. what are the advantages of adding a new library vs. using fetch as is done with other API calls here? Do you suggest transitioning to the new library instead?

Yeah, I would suggest we change all the existing fetch requests to use axios. 
I have noticed in multiple projects that it makes life easier for developers compared to fetch.

Here's a blog post about some of the pros of using axios: https://blog.logrocket.com/axios-or-fetch-api/

**Comment by Rikuoja** [comment]
> Yeah, I would suggest we change all the existing fetch requests to use axios.
> I have noticed in multiple projects that it makes life easier for developers compared to fetch.

Okay, can you give a ballpark figure how long the change should take? Probably not too long, since the function calls are rather similar anyway, or am I mistaken?

**Comment by rBoost** [comment]
> > Yeah, I would suggest we change all the existing fetch requests to use axios.
> > I have noticed in multiple projects that it makes life easier for developers compared to fetch.
> 
> Okay, can you give a ballpark figure how long the change should take? Probably not too long, since the function calls are rather similar anyway, or am I mistaken?

It shouldn't take that long, few hours (2-3).

**Comment by Rikuoja** [comment]
> > > Yeah, I would suggest we change all the existing fetch requests to use axios.
> > > I have noticed in multiple projects that it makes life easier for developers compared to fetch.
> > 
> > 
> > Okay, can you give a ballpark figure how long the change should take? Probably not too long, since the function calls are rather similar anyway, or am I mistaken?
> 
> It shouldn't take that long, few hours (2-3).

Great, I would recommend doing that sooner rather than later, otherwise it is forgotten and we end up with competing ways to call the API in the UI 👍

**Comment by Rikuoja** [comment]
I made a new issue for the other API calls, https://github.com/City-of-Helsinki/linkedevents-ui/issues/466

**Pull request merged**
